// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlh7CI4aQROFS9Wv6Sv1F1F4rEKLap_9I',
    appId: '1:656110812152:web:f330e3df84d2b6c36f340d',
    messagingSenderId: '656110812152',
    projectId: 'asfiex-it14',
    authDomain: 'asfiex-it14.firebaseapp.com',
    storageBucket: 'asfiex-it14.appspot.com',
    measurementId: 'G-23ZYX010HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfPKGHD4tFNDPb2LNQ1mCRo2dvz03HIA',
    appId: '1:656110812152:android:996b475926a375686f340d',
    messagingSenderId: '656110812152',
    projectId: 'asfiex-it14',
    storageBucket: 'asfiex-it14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCumZrJu6BYY3gxJNKV8qLGbJWyQyH9Fc',
    appId: '1:656110812152:ios:706620ea471302896f340d',
    messagingSenderId: '656110812152',
    projectId: 'asfiex-it14',
    storageBucket: 'asfiex-it14.appspot.com',
    iosBundleId: 'com.example.assfiexAppIt14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCumZrJu6BYY3gxJNKV8qLGbJWyQyH9Fc',
    appId: '1:656110812152:ios:706620ea471302896f340d',
    messagingSenderId: '656110812152',
    projectId: 'asfiex-it14',
    storageBucket: 'asfiex-it14.appspot.com',
    iosBundleId: 'com.example.assfiexAppIt14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlh7CI4aQROFS9Wv6Sv1F1F4rEKLap_9I',
    appId: '1:656110812152:web:95a08f779813b97a6f340d',
    messagingSenderId: '656110812152',
    projectId: 'asfiex-it14',
    authDomain: 'asfiex-it14.firebaseapp.com',
    storageBucket: 'asfiex-it14.appspot.com',
    measurementId: 'G-BK2V1EBWBR',
  );
}
